app/modules/servers/models.py
from app.db import db


class Server(db.Document):
    name = db.StringField(required=True)
    ip = db.StringField(required=True)
    description = db.StringField(required=True)
    active = db.BooleanField()
    type_server = db.StringField(required=True)
    deleted = db.BooleanField()

app/modules/servers/forms.py
# -*- coding: utf-8 -*-
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm as Form
# Import Form elements such as TextField and BooleanField (optional)
from wtforms import (
    TextField,
    TextAreaField,
    SelectField,
    BooleanField
)
# Import Form validators
from wtforms.validators import (
    Required,
    Length,
    Optional
)
# Define the login form (WTForms)
type_choices = [('desarrollo', 'Desarrollo'),
                ('produccion', u'Producción'),
                ('otro', 'Otro')]


class ServerForm(Form):
    name = TextField('Nombre',
                     [Required(message='Debe ingresar nombre del Servidor')])
    ip = TextField(u'Ip/Hostname',
                   [Required(
                    message='Debe ingresar la ip/hostname del servidor')])
    type_server = SelectField('Tipo',
                              [Required(message='Debe seleccionar el tipo')],
                              choices=type_choices,
                              coerce=unicode)
    description = TextAreaField(u'Descripción',
                                [Optional(),
                                 Length(max=200)])

app/modules/servers/__init__.py
from flask import Blueprint


servers = Blueprint('servers', __name__)
config = {}
config['name'] = "Servidores"
config['menu'] = {'list': {'link': 'servers.list', 'name': 'Lista'},
                  'create': {'link': 'servers.create', 'name': 'Crear'}}

from controllers import *


def get_config():
    return config

app/modules/servers/controllers.py
"""Controller of inventory."""
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, \
                  jsonify
from flask_login import login_required

import re
# Import the database object from the main app module
import json

from forms import ServerForm, type_choices

# Import module models (i.e. User)
from models import Server

# Define the blueprint: 'auth', set its url prefix: url/auth
from . import servers, config
# from inventory import principal_menu
from app.modules import principal_menu
from app.login import admin, editor, user as viewer


@servers.route('/', methods=['GET'])
@servers.route('/list', methods=['GET', 'POST'])
@login_required
def list():
    """List Method."""
    if request.method == 'POST':
        data = json.loads(request.form.get("args"))
        draw = data['draw']
        length = data['length']
        start = data['start']
        search = data['search']['value']
        result = []
        response = {}
        count = 0
        total = Server.objects.filter(deleted=False).count()
        if search:
            keys = Server._fields.keys()
            keys.remove('id')
            params = [{'deleted': False}]
            regex = re.compile('.*%s.*' % search)
            for key in keys:
                params.append({key: regex})
            try:
                result = Server.objects.filter(__raw__={"$or": params}) \
                                       .limit(length) \
                                       .skip(start)
                count = Server.objects.filter(__raw__={"$or": params}) \
                                      .count()
            except Exception as e:
                print e
        else:
            try:
                result = Server.objects.filter(deleted=False) \
                                       .limit(length) \
                                       .skip(start)
                count = total
            except Exception as e:
                print e

        # order = int(request.form.get('order[0][column]'))
        # order_dir = request.form.get('order[0][dir]')
        response['draw'] = draw
        response["recordsTotal"] = total
        response["recordsFiltered"] = count
        response["data"] = result
        return jsonify(response)
    return render_template("servers/list.html",
                           menu=principal_menu(),
                           config=config,
                           type_choices=dict(type_choices))


@servers.route('/create', methods=['GET', 'POST'])
@editor.require(http_exception=403)
@login_required
def create():
    """Create Method."""
    form = ServerForm(request.form)
    if form.validate_on_submit():
        obj = Server()
        form.populate_obj(obj)
        obj.deleted = False
        Server.objects.insert(obj)
        flash("Servidor creado", "success")
        return redirect(url_for("servers.list"))
    return render_template("servers/create.html",
                           action="create",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@servers.route('/edit/<string:key>', methods=['GET', 'POST'])
@editor.require(http_exception=403)
@login_required
def edit(key):
    """Edit Method."""
    try:
        element = Server.objects.filter(deleted=False,
                                        id=key).first()
    except Exception:
        flash("Servidor No encontrado", "error")
        return redirect(url_for("servers.list"))
    if request.method == 'GET':
        form = ServerForm(request.form, element)
        return render_template("servers/create.html",
                               action="edit",
                               form=form,
                               menu=principal_menu(),
                               config=config)
    else:
        form = ServerForm(request.form)
        if form.validate_on_submit():
            element.update(**form.data)
            flash("Servidor Actualizado", "success")
            return redirect(url_for("servers.list"))
        return render_template("servers/create.html",
                               action="edit",
                               form=form,
                               menu=principal_menu(),
                               config=config)


@servers.route('/view/<string:key>', methods=['GET'])
@login_required
def view(key):
    """Edit Method."""
    try:
        element = Server.objects.filter(deleted=False,
                                        id=key).first()
    except Exception:
        flash("Servidor No encontrado", "error")
        return redirect(url_for("servers.list"))
    form = ServerForm(request.form, element)
    return render_template("servers/create.html",
                           action="view",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@servers.route('/delete/<string:key>', methods=['GET'])
@editor.require(http_exception=403)
@login_required
def delete(key):
    """Delete Method."""
    try:
        element = Server.objects.filter(deleted=False,
                                        id=key).first()
    except Exception:
        flash("Servidor No encontrado", "error")
        return redirect(url_for("servers.list"))
    element.update(deleted=True)
    flash("Servidor Eliminado", "success")
    return redirect(url_for("servers.list"))


@servers.route('/export/<string:type>', methods=['GET'])
@servers.route('/export/<string:type>/<string:key>', methods=['GET'])
@login_required
def export(type='xls', key=None):
    """Export Method."""
    pass

app/templates/servers/create.html
{% extends "layout.html" %}
{% block content %}
        <div class="right_col" role="main">
          <div class="">
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                  {% if request.endpoint == "servers.edit" %}
                    <h2>Editar Servidor<small>{{config['name']}}</small></h2>
                    {% else %}
                    <h2>Crear Servidor<small>{{config['name']}}</small></h2>
                  {% endif %}
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li> -->
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    {% if action == 'view' %}
                    <form class="form-horizontal form-label-left">
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.name.name}}">{{form.name.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        {{form.name(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.ip.name}}">{{form.ip.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        {{form.ip(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.type_server.name}}">{{form.type_server.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.type_server(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>                 
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.description.name}}">{{form.description.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.description(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>  
                    </form>
                    {% else %}
                    <form id="demo-form2" data-parsley-validate method="POST" action="{{ request.path }}" class="form-horizontal form-label-left">
					           {{ form.hidden_tag() }}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.name.name}}">{{form.name.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                     	{% if form.name.errors %}
                     		{{form.name(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                     	{% else %}
                     		{{form.name(class="form-control col-md-7 col-xs-12")}}
                     	{% endif %}
                        </div>
        			            {% if form.name.errors %}
        			        	<ul class="errors text-danger">
                          {% for error in form.name.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                        {% endif %}
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.ip.name}}">{{form.ip.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                       	{% if form.ip.errors %}
                       		{{form.ip(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                       	{% else %}
                       		{{form.ip(class="form-control col-md-7 col-xs-12")}}
                       	{% endif %}
                        </div>
                        {% if form.ip.errors %}
        			        	<ul class="errors text-danger">
        			            {% for error in form.ip.errors %}
        			            	<li>{{ error }}</li>
        			            {% endfor %}
        			        	</ul>
        			        	{% endif %}
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.type_server.name}}">{{form.type_server.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                      {% if form.type_server.errors %}
                        {{form.type_server(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                      {% else %}
                        {{form.type_server(class="form-control col-md-7 col-xs-12")}}
                      {% endif %}
                        </div>
                        {% if form.type_server.errors %}
                        <ul class="errors text-danger">
                          {% for error in form.type_server.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                        {% endif %}
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.description.name}}">{{form.description.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        {% if form.description.errors %}
                          {{form.description(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                        {% else %}
                          {{form.description(class="form-control col-md-7 col-xs-12")}}
                        {% endif %}
                        </div>
                        {% if form.description.errors %}
                        <ul class="errors text-danger">
                          {% for error in form.description.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                        {% endif %}
                      </div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="{{url_for("servers.list")}}" class="btn btn-primary">Cancelar</a>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>
                    </form>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}


<!-- {% with errors = get_flashed_messages(category_filter=["success"]) %}
{% if errors %}
{% for error in errors %}
{{ error }}<br>
{% endfor %}
{% endif %}
{% endwith %}
lista de elementos de inventario -->

app/templates/servers/list.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
    <!-- Datatables -->
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

{% endblock %}
{% block content %}
          <div class="right_col" role="main">
            <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lista de Servidores <small>{{config['name']}}</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li>
                        <a class="close-link">
                          <i class="fa fa-close"></i>
                        </a>
                      </li> -->
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">
                      Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
                    </p>
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Ip/Hostname</th>
                          <th>Tipo</th>
                          <th>Monitoreo</th>
                          <th>Descripción</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tfoot>
                        <tr>
                          <th>Nombre</th>
                          <th>Ip/Hostname</th>
                          <th>Tipo</th>
                          <th>Monitoreo</th>
                          <th>Descripción</th>
                          <th>Acciones</th>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                </div>
              </div>
            </div>
      <form method="post" action="/">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      </form>
          </div>
{% endblock %}
{% block scripts %}
{{ super() }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <!-- <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script> -->
    <!-- <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script> -->

    <!-- Datatables -->
    <script>
      $(document).ready(function() {
        var dtable = $('#datatable-responsive').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
              'url': "{{url_for('servers.list')}}",
              'type': "POST",
              'headers': {'X-CSRFToken': $("input[name=csrf_token]").val()},
              'data': function ( args ) {
                return { "args": JSON.stringify( args ) };
              }
            },
            "columnDefs": [
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        var a = {{ type_choices|tojson }};
                        return a[data] 
                    },
                    "targets": 2
                },
                {
                    "render": function ( data, type, row ) {
                        if(data){           
                          return "<span class='label label-success'>Activo</span>" 
                        }
                        return "<span class='label label-danger'>Inactivo</span>"
                    },
                    "targets": 3
                },
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        html = '<a href="'+'{{url_for("servers.view", key="")}}'+row._id.$oid+'" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Ver </a>\
                         <a href="'+'{{url_for("servers.edit", key="")}}'+row._id.$oid+'" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Editar </a>\
                         <a href="'+'{{url_for("servers.delete", key="")}}'+row._id.$oid+'" class="btn btn-danger btn-xs" onclick="return confirm(`Está seguro que desea borrar este Servidor?`);"><i class="fa fa-trash-o"></i> Eliminar </a>';
                        return html;
                    },
                    "targets": 5,
                    "orderable": false,
                    "width": "20%"
                }
            ],
            "columns": [
              { "data": "name","className":"tr", // can be null or undefined
              "defaultContent": "<i>Not set</i>" },
              { "data": "ip","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"},
              { "data": "type_server", "className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"},
              { "data": "active", "className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"},
              { "data": "description","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"}
              ]
        });
        setInterval( function () {
          dtable.ajax.reload();
        }, 10000 );
      });
    </script>
{% endblock %}
<!-- {% with errors = get_flashed_messages(category_filter=["success"]) %}
{% if errors %}
{% for error in errors %}
{{ error }}<br>
{% endfor %}
{% endif %}
{% endwith %}
lista de elementos de inventario -->